apiVersion: v1
kind: Service
metadata:
  name: gateway-canary
  namespace: navigraph
  labels:
    app: gateway
    track: canary
spec:
  selector:
    app: gateway
    track: canary
  ports:
    - port: 8000
      targetPort: 8000
