apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
  namespace: navigraph
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: managed-csi
  resources:
    requests:
      storage: 1Gi
